### PR TITLE
Upgrade moncycle version

### PR DESCRIPTION
**Pull request by Thovi98**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Thovi98** [comment]
!testme

**Comment by Limezy** [comment]
Hi @Thovi98 may I know why you have abandoned this branch ?
Thanks for trying !

**Comment by Thovi98** [comment]
Because after some some installs on my server (which were successfull), the app did'nt work and I wasn't sure about the way to go 😇

**Comment by Thovi98** [comment]
> Congrats for (I assume) your recent mariage

Thanks! 😇

> Don't forget that a (free) training with official instructors is heavily encouraged for learners. You'll find links on the official moncycle.app website !

I will, thank you for the tip!

**Pull request closed without merging**
